In [11]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [12]:
df=pd.read_pickle(r'C:\Users\anton\Desktop\Master The Power\P_04_Proyecto_EDA\dataframe_limpio.pkl')

df.head()

,edad,ocupacion,estado_civil,nivel_educativo,prestamo_hipotecario,otro_prestamo,metodo_contacto,duracion_ultima_interaccion,contactos_en_campaña,dias_ultimo_contacto,contactos_previos,resultado_campaña_previa,tasa_variacion_empleo,indice_precios_consumidor,indice_confianza_consumidor,tasa_interes_3m,numero_empleados,suscripcion_producto,fecha_interaccion,ingreso_anual,num_niños,num_adolescentes,fecha_alta_cliente,visitas_web_mensuales,num_hijos,tiempo_cliente,antiguedad_cliente,mes_interaccion,dia_interaccion
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,MARRIED,basic.4y,False,False,telephone,261,1,NaN,0,NaN,1.1,93.994,-36.4,4.857,5191.0,False,2019-08-02,161770,1,0,2012-04-04,29,1,89.0,antiguo,agosto,viernes
e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,MARRIED,high.school,False,False,telephone,149,1,NaN,0,NaN,1.1,93.994,-36.4,NaN,5191.0,False,2016-09-14,85477,1,1,2012-12-30,7,2,45.0,antiguo,septiembre,miercoles
3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,MARRIED,high.school,True,False,telephone,226,1,NaN,0,NaN,1.1,93.994,-36.4,4.857,5191.0,False,2019-02-15,147233,1,1,2012-02-02,5,2,85.0,antiguo,febrero,viernes
9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,MARRIED,basic.6y,False,False,telephone,151,1,NaN,0,NaN,1.1,93.994,-36.4,NaN,5191.0,False,2015-11-29,121393,1,2,2012-12-21,29,3,35.0,antiguo,noviembre,domingo
eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,MARRIED,high.school,False,True,telephone,307,1,NaN,0,NaN,1.1,93.994,-36.4,NaN,5191.0,False,2017-01-29,63164,1,2,2012-06-20,20,3,56.0,antiguo,enero,domingo

In [13]:
df['suscripcion_producto'].value_counts()

suscripcion_producto
False    38156
True      4844
Name: count, dtype: int64

In [14]:
df.groupby('suscripcion_producto').mean(numeric_only=True).T

suscripcion_producto                False         True
edad                            39.861724     40.886310
prestamo_hipotecario             0.544973      0.563584
otro_prestamo                    0.176407      0.170727
duracion_ultima_interaccion    220.430208    551.621387
contactos_en_campaña             2.632797      2.050784
dias_ultimo_contacto             6.246935      5.974435
contactos_previos                0.132771      0.498968
tasa_variacion_empleo            0.244499     -1.241247
indice_precios_consumidor       93.602360     93.352406
indice_confianza_consumidor    -40.603748    -39.763109
tasa_interes_3m                  3.810591      2.107420
numero_empleados              5176.032480   5094.543064
ingreso_anual                93324.595031  92584.301197
num_niños                        1.004744      1.005161
num_adolescentes                 0.998821      0.996903
visitas_web_mensuales           16.587850     16.604253
num_hijos                        2.003564      2.002064
tiempo_cliente                  50.818666     42.719601

In [21]:
df.describe(include=str).T

                    count unique                top   freq
ocupacion           42655     11             admin.  10873
estado_civil        42915      3            MARRIED  25999
nivel_educativo     41193      7  university.degree  12722
metodo_contacto     43000      2           cellular  27396
antiguedad_cliente  43000      3            antiguo  37976
mes_interaccion     42752     12          noviembre   3603
dia_interaccion     42752      7            viernes   6212

In [16]:
df.groupby('ocupacion')['suscripcion_producto'].mean()

ocupacion
admin.           0.130139
blue-collar      0.068883
entrepreneur     0.082786
housemaid        0.098842
management       0.112131
retired          0.251955
self-employed    0.108126
services         0.080730
student          0.313400
technician       0.108454
unemployed       0.143932
Name: suscripcion_producto, dtype: float64

In [17]:
df.groupby('estado_civil')['suscripcion_producto'].mean()

estado_civil
DIVORCED    0.101850
MARRIED     0.102119
SINGLE      0.139281
Name: suscripcion_producto, dtype: float64

In [18]:
df.groupby('nivel_educativo')['suscripcion_producto'].mean()

nivel_educativo
basic.4y               0.102847
basic.6y               0.081308
basic.9y               0.078142
high.school            0.108413
illiterate             0.222222
professional.course    0.113201
university.degree      0.137400
Name: suscripcion_producto, dtype: float64

In [19]:
df.groupby('metodo_contacto')['suscripcion_producto'].mean()

metodo_contacto
cellular     0.147430
telephone    0.051589
Name: suscripcion_producto, dtype: float64

In [22]:
df.groupby('mes_interaccion')['suscripcion_producto'].mean()

mes_interaccion
abril         0.111949
agosto        0.114577
diciembre     0.114465
enero         0.116008
febrero       0.111266
julio         0.114111
junio         0.113341
marzo         0.107272
mayo          0.106287
noviembre     0.114904
octubre       0.123645
septiembre    0.102550
Name: suscripcion_producto, dtype: float64

In [23]:
df.groupby('dia_interaccion')['suscripcion_producto'].mean()

dia_interaccion
domingo      0.112539
jueves       0.120684
lunes        0.108865
martes       0.113727
miercoles    0.109717
sabado       0.113714
viernes      0.108339
Name: suscripcion_producto, dtype: float64

In [24]:
df.groupby('antiguedad_cliente')['suscripcion_producto'].mean()

antiguedad_cliente
antiguo     0.101301
nuevo       0.195467
reciente    0.198673
Name: suscripcion_producto, dtype: float64

In [25]:
df.groupby(['ocupacion', 'antiguedad_cliente'])['suscripcion_producto'].mean()

ocupacion      antiguedad_cliente
admin.         antiguo               0.117635
               nuevo                 0.250000
               reciente              0.215655
blue-collar    antiguo               0.065055
               nuevo                 0.030769
               reciente              0.108407
entrepreneur   antiguo               0.075332
               nuevo                 0.083333
               reciente              0.147436
housemaid      antiguo               0.081055
               nuevo                 0.200000
               reciente              0.287234
management     antiguo               0.102717
               nuevo                 0.190476
               reciente              0.181287
retired        antiguo               0.227063
               nuevo                 0.250000
               reciente              0.404858
self-employed  antiguo               0.099773
               nuevo                 0.142857
               reciente              0.177632
services       antiguo               0.069755
               nuevo                 0.187500
               reciente              0.169576
student        antiguo               0.297496
               nuevo                 0.300000
               reciente              0.367647
technician     antiguo               0.099664
               nuevo                 0.233333
               reciente              0.176159
unemployed     antiguo               0.123922
               nuevo                 0.500000
               reciente              0.267717
Name: suscripcion_producto, dtype: float64

In [26]:
df.groupby(['nivel_educativo', 'antiguedad_cliente'])['suscripcion_producto'].mean()

nivel_educativo      antiguedad_cliente
basic.4y             antiguo               0.088047
                     nuevo                 0.227273
                     reciente              0.231850
basic.6y             antiguo               0.073136
                     nuevo                 0.100000
                     reciente              0.154506
basic.9y             antiguo               0.073171
                     nuevo                 0.098039
                     reciente              0.120125
high.school          antiguo               0.096491
                     nuevo                 0.216981
                     reciente              0.197887
illiterate           antiguo               0.250000
                     nuevo                 0.000000
                     reciente              0.000000
professional.course  antiguo               0.102325
                     nuevo                 0.190476
                     reciente              0.192869
university.degree    antiguo               0.125214
                     nuevo                 0.232323
                     reciente              0.219608
Name: suscripcion_producto, dtype: float64

In [28]:
df.groupby(['estado_civil', 'ocupacion'])['suscripcion_producto'].mean()

estado_civil  ocupacion
DIVORCED      admin.           0.100752
              blue-collar      0.075497
              entrepreneur     0.075269
              housemaid        0.093567
              management       0.114706
              retired          0.259669
              self-employed    0.121429
              services         0.060284
              student          0.333333
              technician       0.084367
              unemployed       0.082090
MARRIED       admin.           0.125733
              blue-collar      0.062804
              entrepreneur     0.079535
              housemaid        0.095874
              management       0.109784
              retired          0.257724
              self-employed    0.093319
              services         0.072826
              student          0.190476
              technician       0.104849
              unemployed       0.139605
SINGLE        admin.           0.145593
              blue-collar      0.087645
              entrepreneur     0.102804
              housemaid        0.128000
              management       0.120983
              retired          0.136842
              self-employed    0.140000
              services         0.106902
              student          0.319624
              technician       0.122023
              unemployed       0.188679
Name: suscripcion_producto, dtype: float64